name: Deploy Backend (Hugging Face)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Clone empty HF repo
          git clone https://huggingface.co/spaces/sharjeel17/fashion-cnn hf-space
          
          # Copy backend files into HF repo
          rsync -av --delete backend/ hf-space/
          
          cd hf-space

          git add .
          git commit -m "auto deploy from github actions" || echo "No changes to commit"

          git push https://sharjeel17:$HF_TOKEN@huggingface.co/spaces/sharjeel17/fashion-cnn main